.TA c
.TH criux 8
.ds )H GNU GPL v3
.ds ]W HP-UX Release 11i v1,2,3
.SH NAME
criux \- a simple framework for new korn shell projects
.SH SYNOPSIS

.B criux
.RB [ \-vhfs ]
.IR option ...
.br

.SH DESCRIPTION
The
.B criux
project XYZ and so on
.B criux
creates a nice HTML and plain ASCII documentation. If you like, write your description of the system into
.B some file

example:

